### ISSUE TITLE
Man bliver logget ud efter kort tid (nogle dage??) og skal logge ind igen.

### ISSUE THREAD

**Issue by thomasjensen1194** [morsby/au-medicin-mcq#103]
Jeg aner ikke hvorfor. Måske er cookie sat til at expire indenfor en kort periode?

**Comment by morsby** [comment]
Prøv at teste branchen cookie-expire-#103 -- tror den fikser det (men er ikke så meget inde i sessions m.v.)

**Comment by morsby** [comment]
Ah - den kræver også lige en opdatering i dev.js:

```javascript
const Keygrip = require('keygrip');
let secrets = ['random1','random2'];

module.exports = {
   ...
  keys: Keygrip(secrets),
  ....
```
