### ISSUE TITLE
Mulighed for tilføjelse af personlige kommentarer

### ISSUE THREAD

**Issue by thomasjensen1194** [morsby/au-medicin-mcq#27]

**Comment by thomasjensen1194** [comment]
Der skal tjekkes inden push, hvorvidt kommentarerne lukker når man skifter spørgsmål

**Comment by thomasjensen1194** [comment]
Det gør de ikke, så det skal vi lige have fikset.

**Comment by morsby** [comment]
Det "plejer" jeg at gøre i componentDidUpdate i `Question.js` - så der skal de to `Boolean`s for kommentarstatus lige opdateres.

**Comment by thomasjensen1194** [comment]
Super, det må være fordi jeg har ændret navnet på hver kommentar boolean. Jeg kigger på det.
