### ISSUE TITLE
Åbnes for tagging af spørgsmål

### ISSUE THREAD

**Issue by thomasjensen1194** [morsby/au-medicin-mcq#43]
Specielt er dette godt til 8. semester, hvor specialerne spænder meget bredt. Vi må lige diskutere hvad der er "speciale" og hvad der er et "tag".

Jeg integrerer det sammen med #34

**Comment by morsby** [comment]
Jeg har forestillet mig, at specialer er brede, fx abdominalkirurgi - mens tags så kan være proktologi, cancer, appendicit, akut abdomen m.fl. - om de så skal være overlappende eller ej (f.eks. akut abdomen / appendicit).

**Comment by thomasjensen1194** [comment]
Appendicit tror jeg er lidt for bredt (hvis man skal kunne vælge tags til i sin udvælgelse af spørgsmål). Jeg er enig med proktologi og cancer (men cancer kan måske bare være onkologi).
Men områder, såsom lever, milt, colorectalt osv, kan være brede emner indenfor et speciale. Jeg tænker at tage inspiration fra læselisterne.
