### ISSUE TITLE
Læsegruppe kommentarer

### ISSUE THREAD

**Issue by thomasjensen1194** [morsby/au-medicin-mcq#51]
Mulighed for at tilføje medlemmer til en læsegruppe til ens bruger, som man kan dele kommentarer med.

**Comment by morsby** [comment]
Jeg er modstander. Skal medMCQ virkelig være så socialt et forum? Er det ikke mere oplagt at snakke om et spørgsmål til et reelt møde, i en facebook-tråd el. lign.? Jeg synes, det falder uden for sidens formål.  Kommentarer er i mine øjne ikke ment til reelle diskussioner. 

Det kan evt. tages op, når vi er migreret til SQL. Det bliver så relational, at migreringen heraf nok vil blive besværlig.

**Comment by thomasjensen1194** [comment]
Det var et forslag jeg havde fået af en medstuderende, men synes det er ok at vente - jeg er faktisk også mere for, at man deler sine gode overvejelser offentligt, end at man holder det inden for hver læsegruppe.
